version: "3.4"

services:
  database-service:
    env_file: ./database/credenciais/producao.env
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: container-database
    ports:
      - "3306:3306"
    volumes:
      - ./database/data/mysql:/var/lib/mysql
    networks:
      - estudo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 20

networks:
  estudo_network:
    name: estudo_network
    driver: bridge
